POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "tetytt",
    "number": "11234"
}
###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "tett",
    "number": "11234"
}